using IntelliEngineer.Shared.Enums;

namespace IntelliEngineer.Shared.Models;

/// <summary>
/// 记忆条目模型（三级记忆：全局/项目/角色）
/// </summary>
public class MemoryEntry
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public MemoryLevel Level { get; set; }
    public UserRole? ScopeRole { get; set; }
    public string Key { get; set; } = string.Empty;
    public string Value { get; set; } = string.Empty;
    public double Importance { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime LastAccessedAt { get; set; } = DateTime.Now;
    public int AccessCount { get; set; }
    public string? SourceSessionId { get; set; }
    public bool IsAutoGenerated { get; set; }
}

/// <summary>
/// 记忆压缩后的摘要
/// </summary>
public class MemorySummary
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string SessionId { get; set; } = string.Empty;
    public string Summary { get; set; } = string.Empty;
    public int OriginalMessageCount { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.Now;
}
