using IntelliEngineer.Shared.Enums;

namespace IntelliEngineer.Shared.Models;

/// <summary>
/// 技能包模型（兼容OpenHanako JSON格式）
/// </summary>
public class SkillPackage
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Version { get; set; } = "1.0.0";
    public UserRole TargetRole { get; set; }
    public EngineerSubType? TargetEngineerType { get; set; }
    public SkillFormat Format { get; set; } = SkillFormat.Standard;
    public SkillStatus Status { get; set; } = SkillStatus.Installed;
    public string SystemPrompt { get; set; } = string.Empty;
    public List<string> AllowedTools { get; set; } = new();
    public bool IsAutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.Now;
    public DateTime UpdatedAt { get; set; } = DateTime.Now;
    public string? AuthorId { get; set; }
    public int UsageCount { get; set; }
    public double SuccessRate { get; set; }
}
